### ISSUE TITLE
Show me what you got!

### ISSUE THREAD

**Issue by TaeKimJR** [dsmjs/talk-proposals#10]
## Overview
![image](https://user-images.githubusercontent.com/6180804/39490799-a88e2cd4-4d4f-11e8-9b80-b005cbfb28be.png)

I'd like to start off a presentation series of live-coding called "Show me what you got!". Presenters will live-code a simple app from start-to-finish, talking about the Text Editors/IDEs, libraries, patterns, organizational techniques (and others) that they prefer and why.

I don't know about you, but I'm always curious about what others are using in their day-to-day coding. Plus, as a presenter you may get some great suggestions from the crowd for other ways of doing things!

I'd be happy to start this series off with a React/Redux talk. I've done similar talks in the past, like "The Hipster's Guide to the React Galaxy" talk. I went through the core libraries that I used and live-coded a TODO app.

#### Title
Show Me What You Got (Getting Schwifty w/ React & Redux)

#### Summary
(Live coding) Come checkout how I develop in React and Redux. I'll be going over a simple <TODO> App from start to finish using the patterns, libraries, and organization techniques that I use in my day-to-day coding. I've been using React for the last 4 years and have found the sweet-spot that I'd love to share with ya'll.

#### Is this a talk you've already have prepared or do you still need time to get it ready? How much time would you need to get it ready for a meeting?
I've done similar talks in the past. I'd need about a week to fully prepare.

#### Is this a practice run of a talk that you are giving at another event? If so, when is that event?
Not yet. I have an end-goal of talking at a conference, but yet to find the right topic. I hope to use this talk to up my presentation skills.

#### Would this talk work as a lightning talk or would it fit better as the only talk of the night?
Lightning talk (5-10 min) might be a little tight for the live-coding. I would say 45 min - 1 hour would be perfect.

#### Anything else that would help us decide an appropriate month?
Any month should do. I will be out of the country early June.

#### Contact Info
Email: taekimjr@gmail.com
LinkedIn: https://www.linkedin.com/in/taekimjr/

**Comment by travi** [comment]
@TaeKimJR so sorry for the delay getting back to you. we had a bit of a scramble getting the last meeting together, so we're a little behind following up here.

thanks so much for reaching out to get on our speakers list :) 

it sounds like you have some good ideas here, but i'm not quite sure i follow how it would come together. are you seeing the idea of demoing tools as the focus or a side-effect? when you mention a series of presenters each live coding a simple app, are you thinking they would all demo their tools in the same night, or would it be spread across several meetings? would it be the same simple app for each presenter, or one of their choosing? do you think it would be clear to the audience whether the focus is on the tools or the app?

**Comment by travi** [comment]
sounds great. i will throw out there that it may be difficult to convince additional speakers to follow the same series, so i would be sure to approach your talk as if it were the only talk in the series. we're open to anything on our end that generates more speakers though, so certainly suggest to the group that it would be worthwhile to continue with additional speakers to see if you could spark some interest.

as we work to get this on the calendar, do you happen to have a preferred hosting location or sponsor? certainly not required in any way, but we try to accommodate when there are preferences.

**Comment by TaeKimJR** [comment]
@travi Awesome, I will definitely take that approach.

I do not, I'm open to anywhere and anyone!

**Comment by travi** [comment]
if we put you down for july, would that give you enough time to be prepared?

**Comment by TaeKimJR** [comment]
Yeah! July would be perfect.

**Comment by travi** [comment]
great! the next step would be to either send a PR to the [repo for the current site](https://github.com/dsmjs/dsmjs.github.io) or to respond here with the details you'd like us to include. we'll take care of getting the sponsor and host details and can help you with the details of a PR since we don't have much documented, but we're happy to take care of adding everything if you'd rather just send the info.

**Comment by TaeKimJR** [comment]
Sweet, I'll try that out tonight. I'm excited to present! Thank you for the opportunity.

**Comment by TaeKimJR** [comment]
@travi 
I just opened a PR, sorry it took a bit.
https://github.com/dsmjs/dsmjs.github.io/pull/52

**Comment by travi** [comment]
thanks again for speaking tonight. i think it went great.

if you have slides or code from tonight that you want to link to from our site, fell free to send us a PR with `code` and/or `slides` added to the frontmatter of tonight's meeting
