### ISSUE TITLE
Talk on OAuth flows

### ISSUE THREAD

**Issue by drewiec** [dsmjs/talk-proposals#102]
## Topic
OAuth flows
### Title
OAuth for authentication and authorization

### Summary
At the last meeting there were some questions on the subject and this is a subject I have done some work and research in. I would like to do an overview of the different OAuth flows and how they work. Will probably do it with live coding. React for the front end flows and Node for the back end flows. Kind of expand on the public api talk from last week. Showing how you would implement three legged oauth, so if you wanted to build a client app on top of say Spotify and have your users login you can do so. I don't have all details yet, as the idea recently came to me.

## Scheduling

* is this a talk that you already have prepared or do you still need time to
  get it ready? how much time would you need to have it ready for a meeting?

No, it would take me a couple weeks to out it together.

* is this a practice run for a talk that you are giving at another event? if
  so, when is that event?
Nope.

* would this talk work better as a lightning talk or as the only talk of the
  night?
Probably only talk
* anything else that would help us decide an appropriate month?

* do you have a preferred hosting location?
I am sure we could host at the lean Techniques office.
## Presentation

* will you be presenting from a mac or windows machine? (this gives us an idea
  of what options are available to connect to the presentation equipment)
Mac
* are the ports available limited in any way?
Aren't all Macs port limited?
* do you have your own adapters for connecting to a projector, etc?
Yes
## You

* would you like your name displayed the same as your github profile?
Drew Connelly
* do you have a twitter handle that you would like displayed on the site?
Nope

**Comment by travi** [comment]
@drewiec sorry that it has taken us some time to get back to you about this. I think OAuth could be a valuable topic for the group, but I see that you've closed the issue. Are you still interested in giving this talk?

**Comment by drewiec** [comment]
@travi, It's reopened! Yes I am still interested in giving this talk. Sorry for the confusion!

**Comment by travi** [comment]
Just to confirm, this month's meeting (Tuesday the 10th) would be too early for this talk, correct?

**Comment by drewiec** [comment]
I could do it on the 10th. This is probably about the time I would started putting it together whether I had a month or a week and a half. I have a couple nights this week I can work on it and next weekend. Plenty of time!

**Comment by travi** [comment]
if you're up for it, that would be great. should we use the summary above on the website, or would you prefer any changes?

would you be able to confirm if lean techniques would be willing to host since you mentioned that above? we also like to have a sponsor provide food and drinks for the meeting. the host is welcome to sponsor, but it is also an option for us to find another sponsor for that. we can work out details at leads<at>dsmjs.com, if that would work out.

**Comment by travi** [comment]
also, since this topic is only loosely related to js, it would be great if you could briefly touch on the js relationship. things like a recommended npm library or how it may or may not be recommended to do certain things in the browser vs a node app can be really helpful. don't take the recommendation as any rigid requirement, but hopefully it is helpful for targeting the group somewhat.

**Comment by drewiec** [comment]
Yeah that summary is fine. And confirming that lean Techniques will host. I will get those details to you.

**Comment by drewiec** [comment]
And thats exactly what I wanted to touch on! Was the what to do in the browser and what to do on the backend. And what you shouldn't do in the browser.

**Comment by travi** [comment]
we try to send an estimated count of attendees to our food sponsor the day of the meeting to help with how much to order. is there a specific contact that we should coordinate with for that?

**Comment by drewiec** [comment]
You can just coordinate with me that day.

**Comment by drewiec** [comment]
@travi Do you have a number for tonight?

**Comment by travi** [comment]
we're looking a little lower than normal right now, with 6 signups. that number does not include you as the speaker or our leads.

our typical meetings are ~10-15, so we may see a few more signups or folks just showing up without actually signing up. these numbers are always somewhat fuzzy.

we will try to give you an update closer to lunch as well.

**Comment by drewiec** [comment]
Thanks! We will plan on getting enough for 20 which should cover us either way.

**Comment by travi** [comment]
sounds good. looks like the number is still the same at this point, so i think you have a good target with your plan. i plan to head that direction from the east village around 5:00 so that i can help with any prep that remains before the meeting.

**Comment by travi** [comment]
thanks again for the great talk tonight. i think the group found it useful. if you have any additional details that you'd want included on the site or tweeted out, just let us know.
