### ISSUE TITLE
Fighting Dysfunction with Functional Programming in JavaScript

### ISSUE THREAD

**Issue by micleners** [dsmjs/talk-proposals#103]
### Title

Fighting Dysfunction with Functional Programming in JavaScript

### Summary

You have probably heard of functional programming. Probably a developer you know ranting and raving about how awesome it is. Perhaps you are curious about what functional programming looks like in JavaScript. Maybe you're familiar with the concepts of pure functions and immutability, but want to know more about what it means to apply them. Geared towards JavaScript developers, this talk will explore the functional programming paradigm, how you can use it in your codebase starting today, and how the benefits it will bring. In this talk you can expect code examples for hands-on practice, slides explaining the theory, and, of course, plenty of memes. 

## Scheduling

* is this a talk that you already have prepared or do you still need time to
  get it ready? how much time would you need to have it ready for a meeting?

This is a new talk for me. I'm excited to learn the topic to present on it.

* is this a practice run for a talk that you are giving at another event? if
  so, when is that event?

Yes, I'm applying to several conferences with other talks, including this one.

* would this talk work better as a lightning talk or as the only talk of the
  night?

I'd be happy to share the stage with others interested in presenting on this topic.

* anything else that would help us decide an appropriate month?

April at the earliest.

* do you have a preferred hosting location?

We could ask Source Allies again.

## Presentation

* will you be presenting from a mac or windows machine? (this gives us an idea
  of what options are available to connect to the presentation equipment)

Mac.

* are the ports available limited in any way?

usb-c

* do you have your own adapters for connecting to a projector, etc?

I have dongle

## You

* would you like your name displayed the same as your github profile?

Michael Leners

* do you have a twitter handle that you would like displayed on the site?

micleners

**Comment by travi** [comment]
sounds like a great topic. thanks for giving us a heads up early. be sure to keep us informed as you get closer to being prepared and we can get it on the schedule :)

**Comment by micleners** [comment]
I’m going to close this for now as the timeline for April is not looking good now. Thanks for the interest and perhaps I’ll reopen later this year!
