### ISSUE TITLE
TOPIC: Over mocking/under delivering

### ISSUE THREAD

**Issue by toranb** [dsmjs/talk-proposals#2]
I'm often asked for good examples of over mocking to highlight test friction and decided I would write a talk to show this for anyone unfamiliar with "the cost of over mocking" in tests.

The main focus of the talk is on changing code and how we can keep that low friction in component integration tests. I start out contrasting 2 tests that accomplish the same result. The first has no mocks/spys/stubs and allows us to swap redux middleware without any issue. The other is heavily aware of implementation details (action creator in this example) making changes brittle.

We also exam how the context differs in these 2 scenarios for the next reader (ie: how tests acting like documentation might be impacted one way or another)

**Comment by travi** [comment]
thanks for kicking things off first! seems like a great topic. never a perfect balance in this area, so its always a good idea to keep our eyes open to ways to improve.

some questions that we havent yet gotten into the issue template:
* is this a talk you already have prepared or do you still need time to get it ready? how much time would you need to get it ready for a meeting?
* is this a practice run of a talk that you are giving at another event? if so, when is that event?
* would this talk work as a lightning talk or would it fit better as the only talk of the night?
* anything else that would help us decide an appropriate month?

**Comment by toranb** [comment]
@travi I'm giving this talk today at work actually so it's 100% prepared and ready to rock. I'm happy to delay this until March/April/May if you prefer (to give some new speakers an opportunity to step up).

I /could/ squeeze this down to 10/14 minutes if I had no other option ...but the talk is better at the full 25/30 length (to cover what mocks/stubs/spys are and what problem they solve). If we do this after March I should have time to record it also (for people who cannot make the event in person).

**Comment by travi** [comment]
what would you say to giving this talk in august or september?

**Comment by toranb** [comment]
@travi The only complication in Aug is the week of the 6th (I'm doing a kids web dev workshop) so if we could skip to the following week that might give me some time to prepare :)

Or ... in Sept I'm open the week of 10th + the week of the 17th if either of those might work

**Comment by travi** [comment]
looks like the august meeting would be on the 14th and sept would be the 11th, so i think we'd avoid your conflicts. up to you what works best considering any prep for giving this elsewhere.

**Comment by toranb** [comment]
@travi I like Aug 14th myself - should we book it my friend?

**Comment by travi** [comment]
sorry for the delayed response. busy weekend. august sounds great. we'll work on getting the other details worked out. feel free to send talk details as a PR whenever is convenient for you and we'll get the other details added once we finalize them.

**Comment by toranb** [comment]
@travi I put up a pull request so I assume we can close this issue out?

https://github.com/dsmjs/dsmjs.github.io/pull/53

**Comment by travi** [comment]
thanks again for speaking tonight! looks like you already have code posted for the meeting, so i'll go ahead and close this. you can always send a PR if you have other updates you want us to include

**Comment by toranb** [comment]
Thanks again for having me tonight @travi
