### ISSUE TITLE
Programming Lego Boost with JavaScript

### ISSUE THREAD

**Issue by churchs19** [dsmjs/talk-proposals#21]
### Summary

I've been working on a small project to create a remote control for a Lego Boost-based vehicle using Angular 6, TypeScript, and Node.js. Boost communicates through a Bluetooth Low Energy connection and I thought the community would enjoy learning about what I've learned and seeing the results of this.

### Supporting Info

https://github.com/churchs19/lego-movehub-remote

## Scheduling

* is this a talk that you already have prepared or do you still need time to
  get it ready? how much time would you need to have it ready for a meeting?

This is a project that is still in progress, so I'd likely need a couple of months to have it ready for a meeting. Maybe target October or November 2018?

* is this a practice run for a talk that you are giving at another event? if
  so, when is that event?

Not at this point.

* would this talk work better as a lightning talk or as the only talk of the
  night?

This could easily be either one and could be adjusted for the level of detail required.

* anything else that would help us decide an appropriate month?

Nothing at this point

* do you have a preferred hosting location?

Not really.

## Presentation

* will you be presenting from a mac or windows machine? 
Presenting from Linux on a Surface Pro 3

* are the ports available limited in any way?
I have a mini display port as an output.

* do you have your own adapters for connecting to a projector, etc?
I have a mini display port to HDMI adapter.

## You

* would you like your name displayed the same as your github profile?
Yes. That is fine.

* do you have a twitter handle that you would like displayed on the site?
@shaneschurch

**Comment by travi** [comment]
sorry for the delay getting back to you. sounds like a great topic! its looking like we're probably filled up for speakers for the rest of this year (we usually take a break and don't have a december meeting). what would you think about kicking off the new year by speaking in January?

**Comment by churchs19** [comment]
That sounds good to me.

**Comment by travi** [comment]
great! i'll pencil you in for that slot then. thanks for volunteering!

**Comment by travi** [comment]
hey @churchs19, we still have you down to speak for the January, which looks like it will land on the 8th. Before we head fully into the holidays, we just wanted to make sure that is still going to work for you. Let us know here and we can start getting your details on the site (trying to start early so we don't worry too much about timelines over the holidays).

**Comment by churchs19** [comment]
Yep. That should still be good.
