### ISSUE TITLE
Elm Programming Language

### ISSUE THREAD

**Issue by cartothemax** [dsmjs/talk-proposals#32]
## Topic

Elm Programming Language

### Title

Intro to Elm Programming Language

### Summary

Elm is a purely functional programming language to be used for frontend web development. Elm has great performance, interesting architecture, and most importantly is fun! Come learn the basics of the language along with some functional programming fundamentals.

### Supporting Info

https://slides.com/boots/elm-programming-language

## Scheduling

* is this a talk that you already have prepared or do you still need time to
  get it ready? how much time would you need to have it ready for a meeting?

Talk is ready! 

* is this a practice run for a talk that you are giving at another event? if
  so, when is that event?

This is actually a talk I have given at Iowa Code Camp http://iowacodecamp.com/session/list#50

* would this talk work better as a lightning talk or as the only talk of the
  night?

Only one for the night. The talk is ~1 hour

* anything else that would help us decide an appropriate month?

Nope

* do you have a preferred hosting location?

Hy-Vee HST Offices. I will still need to get the OK for this

## Presentation

* will you be presenting from a mac or windows machine? (this gives us an idea
  of what options are available to connect to the presentation equipment)

Mac

* are the ports available limited in any way?

* do you have your own adapters for connecting to a projector, etc?
Yes, if the projector has an HDMI cable I have the adapter 

## You

* would you like your name displayed the same as your github profile?

Yes please

* do you have a twitter handle that you would like displayed on the site?

No Twitter account

**Comment by cartothemax** [comment]
Asked around our office to determine hosting at HST in Grimes for this meeting. I got the ok from the higher ups! This did come with some stipulations.

- E-Sign Up or at least an estimate of numbers
    - At a certain number (~30+) we would need to move into our gym and we want to be sure to accommodate if numbers required it
- Attendees would need a valid drivers license for entry
- Food sponsorship. Is this something that the hosts typically take care of?

Thanks!

**Comment by travi** [comment]
sorry for the delay in responding. all the info looks great. nice work on the hosting too. 

we already use eventbrite for sign-ups, so we'll have an estimate from that that we normally send around noon the day of the talk. its only as accurate as the people that do sign up, but it usually gives a pretty decent idea. our numbers are normally around 15 or so, but it can vary depending on location. if you have a bunch of people stay or the chance to see the building draws extra people, who knows, but it seems unlikely that we'd hit 30.

when you say that driver's license is needed, does that mean guest badges as well. we can try to mention the extra prep to try to twist arms to actually sign up.

it is great when hosts sponsor food/drinks as well. its always an option to separate things out, but the ideal situation is usually to have the speaker, hosting, and sponsorship all from the same place, if its an option.

**Comment by travi** [comment]
one more question... not important until we post details on the site, but will you want you slides link posted before the talk, or should we wait until afterward?

**Comment by travi** [comment]
oh, and if you're still good with the timing, i'll get you slotted in for february. looks like it'll be the 12th.

**Comment by cartothemax** [comment]
No worries about the delay. We got some time 😄 

>when you say that driver's license is needed, does that mean guest badges as well. we can try to mention the extra prep to try to twist arms to actually sign up.

Yes, when folks come into the building they will need to stop at our front desk and pickup a guest badge. The address is 3801 S James St. Ste 400, Grimes, IA 50111. The building is very nondescript and the entrance is in the SW corner of the building.

>it is great when hosts sponsor food/drinks as well. its always an option to separate things out, but the ideal situation is usually to have the speaker, hosting, and sponsorship all from the same place, if its an option.

We will host food here!

>one more question... not important until we post details on the site, but will you want you slides link posted before the talk, or should we wait until afterward?

We can just post afterwards. Don't want to give the talk details away! It's very secret. 

>oh, and if you're still good with the timing, i'll get you slotted in for february. looks like it'll be the 12th.

February 12th is good for me! Thanks @travi. Let me know if you have any other questions.

**Comment by travi** [comment]
> We will host food here!

perfect

> It's very secret.

👍

**Comment by travi** [comment]
we'll try to get details posted to the website in the next few days. any adjustments you are wanting to make to the summary you posted above?

**Comment by cartothemax** [comment]
Hey @travi, all looks good from my end! I should probably look back over my slides here before the talk 😄 

Let me know if you have any other questions for me.

**Comment by travi** [comment]
could you confirm what i should use as the street address? also, should i use https://www.hy-vee.com/ for the website?

**Comment by travi** [comment]
thanks! i updated https://dsmjs.com with the details. please let me know if you notice anything that needs adjustment. i'll get the eventbrite tracker added soon as well

**Comment by travi** [comment]
oh, since this will be our first time at hyvee, i dont have any pictures of someone speaking there. i usually try to coordinate the eventbrite picture, if possible. do you happen to have any pics of either yourself speaking somewhere, or someone else speaking at hyvee that would make sense for me to use? i can use a pic from a different meeting, if not

**Comment by cartothemax** [comment]
I will see if I can get my hands on one. If not we might just need to rip one off of innovate.hy-vee.com. I will let ya know

**Comment by cartothemax** [comment]
Here ya go @travi 

![hst-82-2-min](https://user-images.githubusercontent.com/413224/52150320-35d84980-2635-11e9-9781-671196ac94ba.jpg)

**Comment by travi** [comment]
@cartothemax realized that i dont have an email, etc to reach out about final details. could you send me a note at [my last name] at dsmjs.com?

**Comment by cartothemax** [comment]
Thanks for making this talk happen @travi!
