### ISSUE TITLE
Building Component Libraries with a Monorepo

### ISSUE THREAD

**Issue by leerob** [dsmjs/talk-proposals#33]
### Title

Building Component Libraries with a Monorepo

### Summary

Learn why your organization needs a component library and discover the best practices for building, scaling, and adopting it across all platforms. We'll be using industry-standard technology (React, JavaScript, Storybook) alongside cutting-edge solutions (CSS-in-JS, Monorepo).

### Supporting Info

There will be slides.

## Scheduling

* is this a talk that you already have prepared or do you still need time to
  get it ready? how much time would you need to have it ready for a meeting?
It's ready! 

* is this a practice run for a talk that you are giving at another event? if
  so, when is that event?
Nope

* would this talk work better as a lightning talk or as the only talk of the
  night?
Will be 40-50 minutes.

* anything else that would help us decide an appropriate month?
Nope

* do you have a preferred hosting location?
It would be _awesome_ to host it at Hy-Vee's tech center in Grimes. I'll try and work with our management to see if this is possible. 

## Presentation

* will you be presenting from a mac or windows machine? (this gives us an idea
  of what options are available to connect to the presentation equipment)
Mac, and I'll try to bring my dongles 🙅‍♂️ 

* are the ports available limited in any way?
Yes. Thanks, Apple.

* do you have your own adapters for connecting to a projector, etc?
My dongle has HDMI out.

## You

* would you like your name displayed the same as your github profile?
Yeah, Lee Robinson.

* do you have a twitter handle that you would like displayed on the site?
Sure, @leeerob.

**Comment by leerob** [comment]
I'd actually like to modify a bit what I would be presenting. Not only will the presentation touch on building the component library, but it will also highlight the repository structure, which is a Monorepo using [Lerna](https://github.com/lerna/lerna) and [Yarn Workspaces](https://yarnpkg.com/lang/en/docs/workspaces/). 

This has allowed us to easily release [x] number of packages from one repo with a shared lint, test, build, and release process.

**Comment by leerob** [comment]
Also, similar to https://github.com/dsmjs/talk-proposals/issues/32, we can host at HST 👍

**Comment by travi** [comment]
thanks for volunteering, @leerob! sorry that we've been slow to respond, but all the info looks great and the topics sound like they'll be interesting to the group. you're totally free to modify as much as you'd like up to the night you speak :) lerna/yarn seem like big enough topics that they could be a whole talk though, so if you think it would be tight to include them in your existing talk, we're also open to you giving multiple talks. totally up to you what makes the most sense tho.

we're excited to get hy-vee into our rotation, but we may try to space your talk out a bit from andrew's, assuming we have a few more speakers sign up before then. we'll keep you informed as we figure out more details about the schedule.

**Comment by leerob** [comment]
@travi Awesome! Thanks so much. Keep me posted.

**Comment by travi** [comment]
would next month's meeting (June 11) work for you to give this talk?

**Comment by leerob** [comment]
Unfortunately no ☹️ I will be out of state then.

**Comment by travi** [comment]
no problem at all. we'll probably try to get you lined up sometime soon, so if there is a month that works well for you, just let us know.

**Comment by leerob** [comment]
September or August would be perfect!

**Comment by michaelwclark** [comment]
@leerob  I'm so sad we couldn't get you at Denim! I've been following your posts and work since you joined Hyvee. Quite impressive. Keep up the good work, and we are all very much looking forward to this presentation. We are 1/2 down the same path here, so I'm sure we can all learn a lot from your experiances in this endevour.

**Comment by travi** [comment]
@leerob does september still work for you?

**Comment by leerob** [comment]
@travi Yeah - what dates did you have in mind?

**Comment by travi** [comment]
sorry, i should have included that to start with. our normal meeting night would be Tuesday, September 12. if possible, we try to stick to the 2nd tuesday of the month, but we have adjusted occasionally when necessary.

**Comment by leerob** [comment]
Tuesday, September 10th?* I am free then.

**Comment by travi** [comment]
wow, yep. sorry for that confusion, haha.

great, if you're free, could you start conversations on your side about hosting/food? we'll pencil you in for that night and can figure out the rest of the details as we get closer.

**Comment by leerob** [comment]
@travi Will do 👍 I sent an email out - will follow up once confirmed.

**Comment by leerob** [comment]
We've started the conversations on our side about hosting and food. We should be good to go. Let me know once there's an Eventbrite link so we can figure out the estimated headcount 👍 Thanks!

**Comment by leerob** [comment]
Here's updated info for the talk.

**Title:** *Building Component Libraries with a Monorepo*

**Description:** Learn why your organization needs a component library and discover the best practices for building, scaling, and adopting it across all platforms. We'll be using industry-standard technology (React, JavaScript, Storybook) alongside cutting-edge solutions (CSS-in-JS, Monorepo).

**Bio:** Lee Robinson is a developer, writer, and UI/UX enthusiast. He works at Hy-Vee, a $10 billion dollar grocery chain in the Midwest. His primary focus is developing Aisles Online, Hy-Vee's e-commerce grocery shopping platform, which serves millions of customers every year. 

Outside of his normal work as an engineer, he helps attract and recruit the best talent to support Hy-Vee's ambitious growth. Prior to Hy-Vee, Lee worked as an engineer at Workiva (NYSE:WK) - a cloud provider of connected data, reporting, and compliance solutions. Lee enjoys all things technology, music, and photography/videography.

**Comment by travi** [comment]
thank you for the additional detail. i'm planning to get this posted to the website in the next few days. i'll confirm here once its up.

**Comment by travi** [comment]
finally got back around to getting eventbrite wired up. we'll start marketing on twitter early next week

**Comment by michaelwclark** [comment]
@leerob  I sent you an email to your personal address with the names. We are at about registered.
