### ISSUE TITLE
Serverless Webhooks

### ISSUE THREAD

**Issue by therockstorm** [dsmjs/talk-proposals#39]
## Topic

Serverless Webhooks

### Title

Send Webhooks in Seconds with Serverless

### Summary

At Dwolla, we send millions of webhooks a week. We recently rearchitected from a single shared queue serviced by a cluster of Scala workers to a queue and TypeScript Lambda worker per partner. This increased reliability, decreased costs, and cut delays from 60 minutes during peak load to under one. Join us for valuable lessons learned and a walkthrough of the open-sourced code!

### Supporting Info

Haven't completed the slides and in the process of getting legal approval to open source the code.

## Scheduling

* is this a talk that you already have prepared or do you still need time to
  get it ready? how much time would you need to have it ready for a meeting?

I can have it ready for April.

* is this a practice run for a talk that you are giving at another event? if
  so, when is that event?

No

* would this talk work better as a lightning talk or as the only talk of the
  night?

Only one of the night

* anything else that would help us decide an appropriate month?

I'm moving out of Des Moines in June so April works best, May could work.

* do you have a preferred hosting location?

Dwolla's new office, pending approval

## Presentation

* will you be presenting from a mac or windows machine? (this gives us an idea
  of what options are available to connect to the presentation equipment)

Mac

* are the ports available limited in any way?

No

* do you have your own adapters for connecting to a projector, etc?

Yes

## You

* would you like your name displayed the same as your github profile?

Yes

* do you have a twitter handle that you would like displayed on the site?

No Twitter, but you could use rockywarren.com.

**Comment by travi** [comment]
April should work great on our end as well. I'll put you on the schedule. Sounds like a great talk. Looking forward to hearing more!

**Comment by travi** [comment]
timing is getting to the point where we should start getting this up on the website. does the summary above still cover what you would want posted?

**Comment by therockstorm** [comment]
I updated the summary above and have legal approval to open source the code. The slides are complete and are in the repo.

**Comment by travi** [comment]
[The website](https://dsmjs.com) is updated, so let us know if you notice any details that need to be tweaked. We'll try to get a tweet or two out next week, but Dwolla is welcome to market as much as you would like in addition. Feel free to link to https://dsmjs.com to encourage signing up if you do send out any marketing.
