### ISSUE TITLE
REST to GraphQL

### ISSUE THREAD

**Issue by jrmeier** [dsmjs/talk-proposals#43]
## Topic
GraphQL 
### Title

REST to GraphQL, The easy way

### Summary
Demonstrating how to go from a standard, MongoDB backed REST API to a GraphQL service.

### Supporting Info

This will be added after as I get the presentation complete, with code and slides.

## Scheduling

* I can have this talk ready in few days.

* I'm aiming for 35-45 minutes total, plus questions at the end.

* We can host at 700 Locust, Suite 304 (our office).

## Presentation

* MacOS

* I have all the adapters I would need.

## You

* would you like your name displayed the same as your github profile? Yes, (jrmeier)

* do you have a twitter handle that you would like displayed on the site? No

**Comment by michaelwclark** [comment]
Looking forward to hearing you speak and having Denim host for May 14th. Please open a PR for https://github.com/dsmjs/dsmjs.github.io to add your talk and meeting info. Please don't hesitate to reach out with any questions.
