### ISSUE TITLE
Serverless through AWS SAM

### ISSUE THREAD

**Issue by tbrunia** [dsmjs/talk-proposals#7]
Will describe what serverless is and why it's gaining traction in the software engineering community. As an example, I'll share [a reference implementation](https://www.github.com/xilution/xilution-react-todomvc) that highlights [AWS SAM](https://github.com/awslabs/serverless-application-model) (Serverless Application Model).

**Comment by travi** [comment]
thanks for submitting!

a few follow up questions since we haven't added an issue template yet: 
* is this a talk that you already have prepared or do you still need time to get it ready? how much time would you need to have it ready for a meeting? we are looking for a speaker as soon as the next meeting if you'd like to speak that early
* is this a practice run for a talk that you are giving at another event? if so, when is that event?
* would this talk work better as a lightning talk or as the only talk of the night?
* anything else that would help us decide an appropriate month?
* do you have a preferred hosting location?

**Comment by tbrunia** [comment]
> is this a talk that you already have prepared or do you still need time to get it ready? how much time would you need to have it ready for a meeting? we are looking for a speaker as soon as the next meeting if you'd like to speak that early

I haven't given the talk yet, but I plan to present it in as many forums as I can this spring and summer. The talk will center on [a public repo](https://github.com/xilution/xilution-react-todomvc) that I'm putting together which highlights AWS SAM and Xilution SaaS. (Mostly focused on AWS SAM. I will work in a little plug for Xilution SaaS. The reference implementation's back end integrates with a couple of Xilution SaaS products.) I still need a couple of 2-3 weeks to wrap up the project. I'm scheduled to do a first pass of the presentation to my Source Allies teammates on May 14th.

> is this a practice run for a talk that you are giving at another event? if so, when is that event?

Not necessarily a practice run, but will use feedback from your membership to improve the talk. So far, I'm scheduled to give the talk to my Source Allies teammates and I'm also in discussions with Des Moines Web Geeks.

> would this talk work better as a lightning talk or as the only talk of the night?

If it complements other topics, a lightning talk would be cool; however, I think the topic needs a full hour to present. Serverless is new to a lot of people, so I plan to cover serverless at a general level then dive into to the repo as a reference implementation with ample time for questions.

> anything else that would help us decide an appropriate month?

I'm flexible. I would prefer to give the talk at SAI first on May 14th.

> do you have a preferred hosting location?

A digital agency would be preferred (Xilution target market). We can host at Source as well.

**Comment by travi** [comment]
> I'm flexible. I would prefer to give the talk at SAI first on May 14th.

would you want to speak in June, or would you rather push it out further than that?

**Comment by travi** [comment]
> June works for me.

Great! Once we are past next week's meeting, we'll reach out for a few more details so we can get it posted to the site. Looking forward to the talk

> I’m on vacation between June 22nd and June 29th though.

Not a problem. The June meeting will be on Tuesday, the 12th.

**Comment by travi** [comment]
Sorry for the delay getting back to this after the last meeting. At this point we just need to confirm host/sponsor and get details posted on the site. 

I don't think we have a sponsor that would really fit the agency target. Short of that, is Source what you'd like to go with? If so, do you want to work out details with Carter, or would you rather we coordinate with him?

As far as getting details on the site, do you want to send us a PR to update the site directly (we would walk you through the details), or would you rather just send us the title and description?

**Comment by tbrunia** [comment]
@travi, I just had something come up at work. I'll be out of town on Tuesday night. Can we postpone the June 12th meeting? I'm available on June 14th or June 19th.

**Comment by travi** [comment]
ok. since Source is hosting, that simplifies things quite a bit. the biggest risk is just that moving the date from normal could cost some attendance. we are thinking that the 19th would be the better option if that works out, so lets try for that for now. thanks for giving us the heads up early :)

**Comment by tbrunia** [comment]
Thanks, Matt. We’ll do the 19th then. I’ll make a PR to the update the date on the site. Source is onboard with hosting on the 19th.

**Comment by tbruniasai** [comment]
:octocat: This PR: https://github.com/dsmjs/dsmjs.github.io/pull/51/commits to the dsm.js site to change the date from 6/12 to 6/19.
