### ISSUE TITLE
Gatsby + Contentful + Netlify

### ISSUE THREAD

**Issue by micleners** [dsmjs/talk-proposals#79]
## Topic
Frontend framework. Headless CMS. Static site deployment.

### Title
Becoming Contentful with Your Gatsby Static Site on Netlify

### Summary
JAMStack, say what? Publishing blazing fast and secure websites has never been easier or so free. This talk should be accessible to all, but experience in CMS structure, React, Gatsby, Netlify (or similar) deployment will help! In this talk you can expect to learn about these new technologies and what do they do. How to start a new Gatsby site (or how to start the one I built). How to setup Contentful and create your first model and content. How to link Contentful and Gatsby, use GraphQL to fetch this data and display it on your website. How to use Gatsby’s GraphQL playground to test queries. Finally you'll see how to deploy to Netlify and connect Contentful to Netlify to trigger builds when your data changes.

### Supporting Info
Will work on this

## Scheduling
I am building my site currently, will need to make the presentation. I am submitting this talk for Iowa Code Camp on October 29. I'm opening to presenting in October or November. I'm open to where ever you'd like to have it. We can talk to Source Allies (my employer) about hosting it if we need to pin down a location.

## Presentation
I will be presenting on a Mac with a dongle to HDMI

## You
- Name: Michael Leners
- Github and Twitter: @micLeners
- Website: https://micleners.com/

**Comment by travi** [comment]
sounds like a great topic. we don't have a speaker for october yet, so we'd love to put you down for then since it sounds like you'd be up for it. we're happy to come to source allies if that's easiest for you.

**Comment by micleners** [comment]
Sweet deal. October could work! Second Tuesday? We'd have to pitch it to our Teammate Services - have you ever had it at SA before?

**Comment by travi** [comment]
yep, second tuesday, which looks like it will fall on 10/08. source allies has been a great host for us in the past, so we've come there several times in the past. thanks for reaching out! we'll put you down :)

**Comment by travi** [comment]
@micleners i just got these details posted to [the site](https://dsmjs.com). let me know if you see anything that you'd like tweaked. we'll get a tweet out in the morning to start the marketing process.

**Comment by micleners** [comment]
Awesome. I was actually gearing up for my first Hacktober PR to the dsmJS
repo when I saw that it had been updated! 😂 thanks and sounds good. I’ll
keep an eye out for the tweet so I can retweet.

**Comment by travi** [comment]
https://twitter.com/desmoinesjs/status/1179021177592975362 ;)

sorry we blocked your first hacktoberfest PR. we have a few gatsby tasks that are outstanding on the new site if you happen to be looking for things to contribute to this month :)

**Comment by micleners** [comment]
That’s perfect timing giving what I’m trying to get into. I’ll check into
those tasks

**Comment by travi** [comment]
we probably dont have things very well (if at all) documented in issues at this point. what's out there is probably even out of date. feel free to bug me on dsm web collective if youre interested in picking some stuff up though. i'd be happy to work out what could be valuable.
